export enum VIEWS {
  LOADING = 0,
  DASHBOARD = 2,
  SHOW_CAMPAIGNS = 3,
  GENERATE_API_KEY = 4,
  CREATE_CAMPAIGN = 10,
}

export enum CREATE_CAMPAIGN_VIEWS {
  LEVEL1 = 10,
  LEVEL2 = 11,
  LEVEL3 = 12,
}
